const runtimeInspectorRows = [
  {
    id: '5173',
    port: 5173,
    protocol: 'TCP4',
    address: '127.0.0.1',
    app: 'node',
    service: 'Vite dev server',
    project: 'dsh-port-inspector',
    projectPath: 'D:\\project\\dsh-port-inspector',
    pid: 18824,
    created: '2026-08-23 14:32:08',
    source: 'confirmed',
    session: '当前会话',
    sessionTitle: 'dsh-port-inspector',
    requestSummary: '启动 Vite 开发服务并监听 5173 端口',
    sessionId: 'sess_4f2a…91c',
    turn: '18',
    step: '3',
    callId: 'call_7f3a…b12',
    rootCallId: 'call_7f3a…b12',
    tool: 'terminal',
    ownerKind: 'Terminal',
    ownerId: 'pty-1',
    action: 'managed',
    actionLabel: '可由 DSH 停止',
    sourceHint: 'PID、创建时间与父链完整匹配',
  },
  {
    id: '3000',
    port: 3000,
    protocol: 'TCP4',
    address: '0.0.0.0',
    app: 'node',
    service: 'Next.js development server',
    project: 'web-console',
    projectPath: 'D:\\project\\web-console',
    pid: 20116,
    created: '2026-08-23 14:24:51',
    source: 'confirmed',
    session: '当前会话',
    sessionTitle: 'dsh-port-inspector',
    requestSummary: '后台启动 Next.js 开发服务并监听 3000 端口',
    sessionId: 'sess_4f2a…91c',
    turn: '17',
    step: '6',
    callId: 'call_35cd…e04',
    rootCallId: 'call_35cd…e04',
    tool: 'run_in_background',
    ownerKind: 'Job',
    ownerId: 'ri-gate-background-1',
    action: 'managed',
    actionLabel: '可由 DSH 停止',
    sourceHint: 'PID、创建时间与父链完整匹配',
  },
  {
    id: '8080',
    port: 8080,
    protocol: 'TCP4',
    address: '127.0.0.1',
    app: 'node',
    service: 'legacy-dashboard',
    project: 'legacy-dashboard',
    projectPath: 'D:\\workspace\\legacy-dashboard',
    pid: 22540,
    created: '2026-08-23 12:08:19',
    source: 'clue',
    session: '来源未确认',
    sessionId: '—',
    turn: '—',
    step: '—',
    callId: '—',
    rootCallId: '—',
    tool: '—',
    ownerKind: '',
    ownerId: '',
    action: 'external',
    actionLabel: '可结束单个进程',
    sourceHint: '发现 DSH 线索，但未完成身份核验',
  },
  {
    id: '9229',
    port: 9229,
    protocol: 'TCP4',
    address: '127.0.0.1',
    app: 'node',
    service: 'Node inspector',
    project: '—',
    projectPath: '',
    pid: 24008,
    created: '—',
    source: 'unknown',
    session: '来源未确认',
    sessionId: '—',
    turn: '—',
    step: '—',
    callId: '—',
    rootCallId: '—',
    tool: '—',
    ownerKind: '',
    ownerId: '',
    action: 'readonly',
    actionLabel: '仅可查看',
    sourceHint: '未找到可靠 DSH 关联，进程身份信息不完整',
  },
  {
    id: '4173',
    port: 4173,
    protocol: 'TCP6',
    address: '::1',
    app: 'node',
    service: 'Storybook preview',
    project: 'ui-sandbox',
    projectPath: 'D:\\workspace\\ui-sandbox',
    pid: 26480,
    created: '2026-08-23 11:42:27',
    source: 'unknown',
    session: '来源未确认',
    sessionId: '—',
    turn: '—',
    step: '—',
    callId: '—',
    rootCallId: '—',
    tool: '—',
    ownerKind: '',
    ownerId: '',
    action: 'external',
    actionLabel: '可结束单个进程',
    sourceHint: '未找到可靠 DSH 关联',
  },
  {
    id: '6006',
    port: 6006,
    protocol: 'TCP4',
    address: '0.0.0.0',
    app: 'dotnet',
    service: 'API service',
    project: '—',
    projectPath: '',
    pid: 27304,
    created: '—',
    source: 'unknown',
    session: '来源未确认',
    sessionId: '—',
    turn: '—',
    step: '—',
    callId: '—',
    rootCallId: '—',
    tool: '—',
    ownerKind: '',
    ownerId: '',
    action: 'readonly',
    actionLabel: '仅可查看',
    sourceHint: '未找到可靠 DSH 关联，无法读取完整身份',
  },
]

Object.assign(window, { runtimeInspectorRows })
