// Generated by scripts/update-toolchain-logos.mjs from assets/toolchains; do not edit by hand.
import toolchainLogoAdb from 'toolchain-assets/adb.png'
import toolchainLogoAnthropic from 'toolchain-assets/anthropic.png'
import toolchainLogoBun from 'toolchain-assets/bun.png'
import toolchainLogoClaudeCode from 'toolchain-assets/claude-code.png'
import toolchainLogoCodex from 'toolchain-assets/codex.png'
import toolchainLogoCursor from 'toolchain-assets/cursor.png'
import toolchainLogoDeno from 'toolchain-assets/deno.png'
import toolchainLogoDjango from 'toolchain-assets/django.png'
import toolchainLogoDocker from 'toolchain-assets/docker.png'
import toolchainLogoFastapi from 'toolchain-assets/fastapi.png'
import toolchainLogoFirebase from 'toolchain-assets/firebase.png'
import toolchainLogoFlask from 'toolchain-assets/flask.png'
import toolchainLogoGemini from 'toolchain-assets/gemini.png'
import toolchainLogoGithubCopilot from 'toolchain-assets/github-copilot.png'
import toolchainLogoGo from 'toolchain-assets/go.png'
import toolchainLogoJetbrains from 'toolchain-assets/jetbrains.png'
import toolchainLogoMariadb from 'toolchain-assets/mariadb.png'
import toolchainLogoMetro from 'toolchain-assets/metro.png'
import toolchainLogoMongodb from 'toolchain-assets/mongodb.png'
import toolchainLogoMysql from 'toolchain-assets/mysql.png'
import toolchainLogoNextjs from 'toolchain-assets/nextjs.png'
import toolchainLogoNodejs from 'toolchain-assets/nodejs.png'
import toolchainLogoOllama from 'toolchain-assets/ollama.png'
import toolchainLogoOpenai from 'toolchain-assets/openai.png'
import toolchainLogoPhp from 'toolchain-assets/php.png'
import toolchainLogoPostgresql from 'toolchain-assets/postgresql.png'
import toolchainLogoPython from 'toolchain-assets/python.png'
import toolchainLogoRedis from 'toolchain-assets/redis.png'
import toolchainLogoRuby from 'toolchain-assets/ruby.png'
import toolchainLogoSpring from 'toolchain-assets/spring.png'
import toolchainLogoVite from 'toolchain-assets/vite.png'
import toolchainLogoVscode from 'toolchain-assets/vscode.png'

export const TOOLCHAIN_LOGO_DATA = {
  "adb": toolchainLogoAdb,
  "anthropic": toolchainLogoAnthropic,
  "bun": toolchainLogoBun,
  "claude-code": toolchainLogoClaudeCode,
  "codex": toolchainLogoCodex,
  "cursor": toolchainLogoCursor,
  "deno": toolchainLogoDeno,
  "django": toolchainLogoDjango,
  "docker": toolchainLogoDocker,
  "fastapi": toolchainLogoFastapi,
  "firebase": toolchainLogoFirebase,
  "flask": toolchainLogoFlask,
  "gemini": toolchainLogoGemini,
  "github-copilot": toolchainLogoGithubCopilot,
  "go": toolchainLogoGo,
  "jetbrains": toolchainLogoJetbrains,
  "mariadb": toolchainLogoMariadb,
  "metro": toolchainLogoMetro,
  "mongodb": toolchainLogoMongodb,
  "mysql": toolchainLogoMysql,
  "nextjs": toolchainLogoNextjs,
  "nodejs": toolchainLogoNodejs,
  "ollama": toolchainLogoOllama,
  "openai": toolchainLogoOpenai,
  "php": toolchainLogoPhp,
  "postgresql": toolchainLogoPostgresql,
  "python": toolchainLogoPython,
  "redis": toolchainLogoRedis,
  "ruby": toolchainLogoRuby,
  "spring": toolchainLogoSpring,
  "vite": toolchainLogoVite,
  "vscode": toolchainLogoVscode
} as const
